reload.sh
start.sh

Removed empty lines with `\r` character in it.

Fix windows related issue in shell scripts

---

api/auth/auth.py
demogen/demogen.py
openpype/entities/models/fields.py
openpype/entities/models/generator.py
schemas/schema.project.sql

Moving files out of the representation.data to a separate JSONb column.
This is a work in progress.

Representation files model

---

ARCHITECTURE.md

This document gives a bird's eye overview of the package, and hopefully helps onboarding and contributions, allowing people to find what they are looking for faster.

documentation: Add `ARCHITECTURE.md` document.

---

ayon_server/addons/models.py
ayon_server/settings/models.py

Added option to pass custom filename to http source as the filename may not be received from url itself.

FileSources: Add 'filename' to http source

---

ayon_server/settings/validators.py

Modified `normalize_name` to match most of usecases in settings and give more options to do when needed.

Settings: Function 'normalize_name' has more options

---

demogen/demogen.py

Use data to fill representation template, that are matching data expected in production. Also auto-fix invalid templates.

Demogen: Use right values in representation template

---

ayon_server/types.py

Unify various regular expressions used for string validation in Ayon server

regex clean-up

---

api/addons/project_settings.py
api/addons/studio_settings.py
api/settings/settings.py
ayon_server/addons/library.py
ayon_server/api/server.py

Provide endpoint to set addon settings without addon actually loaded without validation to provide a way to fix broken settings

Low level access to addon settings

---

api/operations/operations.py

operations endpoint now returns 400 error, if the same entity have multiple update or delete operations requested.
In order to update or delete an entity, it is loaded first and in case of UPDATE, it is opened with "SELECT FOR UPDATE". That means the row is locked until the transaction is finished. If an entity is requested to update multiple times, the second attempt to load it is blocked and the request eventually timeouts and the Postgres connection is not freed from the connection pool. 
This is a critical fix as inactive connections eventually fills up the pool and further DB requests are blocked.

Prevent duplicate operation targets

---

api/marketplace/__init__.py
api/marketplace/common.py
api/marketplace/marketplace.py
api/marketplace/router.py
pyproject.toml

MVP implementation of endpoins for querying data from the future addon marketplace

Marketplace endpoints

---

api/resolve/__init__.py

Adding `?pathOnly=true` to `/api/resolve` limits the resultset so, items in "entities" array only contain "filePath"

Added pathOnly query argument to /api/resolve

---

.pre-commit-config.yaml
api/addons/__init__.py
ayon_server/addons/library.py
ayon_server/api/server.py
ayon_server/entities/user.py

Addon list (`/api/addons`) now returns broken addon versions in the result (marked with `isBroken: bool` attribute)

Return broken versions in addon list

---

api/operations/operations.py

Each operation in operations response now returns a status code as it would return if standard CRUD functions were used.
It could be used to determine what failed, regardless the 'human-readable' message in the detail field

Return status code in operation result

---

ayon_server/metrics/__init__.py
ayon_server/metrics/events.py

- **add event count query**
- **connect to metrics collector**

collect event topics statistics

---

ayon_server/config.py
ayon_server/lib/redis.py

see https://github.com/ynput/ayon-backend/issues/124

Added redis_key_prefix configuration directive

---

ayon_server/entities/models/__init__.py

Solves: https://github.com/ynput/ayon-backend/issues/155
Tests: https://github.com/ynput/ayon-tests/commit/3f820c5d1c137d43e8d49167ef84b1f89a97c69a

Optional explicit ID for project level entities post requests

---

ayon_server/auth/password.py
ayon_server/auth/session.py

https://github.com/ynput/ayon-backend/issues/156

Create events to track user login and logout

---

ayon_server/activities/create_activity.py
ayon_server/activities/delete_activity.py
ayon_server/activities/event_hook.py
ayon_server/activities/references.py
ayon_server/activities/update_activity.py
ayon_server/activities/utils.py

Added docstrings and comments explaining how ayon_server.activities module works.

Activity feed docstrings and comments

---

api/users/avatar.py
api/users/users.py

-   [ ] This comment contains a description of changes
-   [ ] Referenced issue is linked

Fix avatar caching

---

api/desktop/deps.py
api/desktop/installers.py

-   [x] Referenced issue is linked
`create_dependency_package` and `create_installer` endpoints accept `?overwrite=true` query argument to force overwriting the existing manifest if there was one. Since for similar use cases we use `force` parameter, this unified the naming with the rest of the rest API.
The original parameter still works but it's now deprecated.
Additionally this PR removes long deprecated aliases for dependencyPackages endopints (with underscores). It should have been long gone.

Desktop: Replace `overwite` query parameter with `force`

---

ayon_server/activities/create_activity.py
ayon_server/activities/models.py
ayon_server/activities/references.py
ayon_server/activities/update_activity.py
ayon_server/activities/utils.py
ayon_server/entities/task.py
ayon_server/graphql/resolvers/activities.py

When an activity is created or updated, references to relevant users are created. This is useful to display relevant information to users within the project scope and later as the source of truth for inbox.
Relations are created for:
- folders: assignees on the task within the folder
- tasks: assignees
- versions: author, assignees on the linked task
More relations may be created in the future as this feature is extendable. Additionally, we should consider opting-out from creating the references as we figure out, which ones are really relevant to the users.
New concepts:
- `entityNames` filter in activities graphql resolver
- `role` field in activities.referenceData (can be `assignee` or `author`, but do not rely the value is present, since data may be from server version `<1.1.2` ) …

Activity feed: create user relations for version and folder entities

---

api/activities/__init__.py
api/activities/router.py
api/activities/suggest.py
ayon_server/suggestions/folder.py
ayon_server/suggestions/models.py
ayon_server/suggestions/task.py
ayon_server/suggestions/version.py

Implements server-side resolving for entity autosuggestion in comments

Activity Feed: comment auto suggestions

---

ayon_server/auth/session.py

-   [x] This PR is amazing
-   [x] Referenced issue is linked - no, but hey it's still amazing!
Added a space.
The space makes this:
Turn nice so that there's a space between the word "user" and the actual username.
Yes, blown away by my first backend contribution?
I understand. Remain calm, sit down, take a deep breath. Take one more breath.
Just realize that one day _you_ may also contribute amazing feature enhancements like this.
All it really takes is a spacebar.
Because with every space we raise the bar.

Fix log message formatting

---

ayon_server/settings/enum.py

Introduced new helper functions to enumerate settings, filtering applications as per user input. Retrieve and present a curated list of tools from the database.

Add application and tools enumeration functions.

---

api/system/metrics.py
ayon_server/background/metrics_collector.py
ayon_server/config.py
ayon_server/metrics/__init__.py
ayon_server/metrics/system.py

Refactored metrics system, added storage utilization

System metrics refactor

---

api/files/files.py
api/files/video.py

replaces /files/{file_id}?preview=true with /files/{file_id}/thumbnail

Unified project files serving

---

ayon_server/background/clean_up.py
ayon_server/background/workers.py

Unifies clean-up process for thumbnails, actions and files

Unified clean-up background process

---

ayon_server/events/enroll.py
schemas/schema.public.sql

Judging by preliminary tests, this should speed-up enroll endpoint at least 40x with large events tables.

Use CTE for enroll event resolver

---

api/access_groups/access_groups.py

Non-existent access group no longer polute user data

Access groups: clean up user access groups when an access group is deleted

---

ayon_server/config.py
ayon_server/helpers/deploy_project.py
ayon_server/lib/postgres.py
ayon_server/metrics/system.py

Various postgres optimizations for servers under a heavy load

Database connection optimizations

---

ayon_server/entities/user.py

The linked issue has been opened for a while and i am not sure if there's a consensus whether this is a bug or feature. I've implemented it anyways, so maybe @mkolar or @dee-ynput could decide whether to merge it or not :)

Unassign user from tasks upon deletion

---

ayon_server/actions/execute.py

-   [ ] Referenced issue is linked
Include action identifier in default description
Cosmetics.
To test:
1. Emit some web actions
2. If no 'message' was provided with the action, then the action identifier should be included.

Include action identifier in default description

---

ayon_server/graphql/nodes/kanban.py
ayon_server/graphql/resolvers/kanban.py

GraphQL: Add priority field to Kanban node

---

ayon_server/files/project_storage.py
ayon_server/files/s3.py
ayon_server/helpers/hierarchy_cache.py
ayon_server/lib/postgres.py
ayon_server/utils.py

Mantenance fixes for hierarchy dump and restore

Functions for file uploads

---

api/users/users.py
schemas/schema.project.sql
schemas/schema.public.update.sql

- Drops project.files.author foreign key to allow importing files from external dumps. 
- Handle more data changes when user is renamed (activities, activity references)

Database: allow importing files with unknown author

---

api/onboarding/release.py
api/system/info.py
api/system/sites.py
ayon_server/utils.py

This pull request introduces several changes to the `api/info` endpoint  The key changes include the addition of Redis caching, refactoring of site information retrieval, and improvements to the onboarding status checks.

/api/info performance improvements

---

api/projects/anatomy.py
ayon_server/helpers/deploy_project.py
ayon_server/helpers/extract_anatomy.py

- Fixes wrong key for staging directories when converting anatomy object to project data
- Adds extract_anatomy helper functions, that is needed from time to time in addons (namely Kitsu)

Fix: Saving staging directories to existing project anatomy

---

ayon_server/settings/__init__.py
ayon_server/settings/enum.py

Added `link_types_enum` function to `ayon_server.settings.enum`

Settings: add link types enum resolver

---

api/thumbnails/thumbnails.py

Publishing from the current version of maya uploads png thumbnail, but reports "image/jpeg" mime-type (or vice versa). That breaks publishing due to the strict check introduced in Ayon 1.5.5. Since we can determine the mimetype on the server from the payload headers, we just log the warning instead returning an error response.

Warn when thumbnail mime mismatches instead of returning an error

---

schemas/schema.public.sql
setup/__main__.py

This pull request includes changes to the database schema and the initialization script to support tracking server updates. The key changes are the addition of a new table for storing server updates and the modification of the initialization script to record the current server version upon update.

Track server updates in the database

---

schemas/migrations/00000004.sql
schemas/schema.project.sql

This pull request includes changes to the database schema. 
The main updates are the addition of `tags` column to `activities` table and various new indexes to the `activities` and `activity_references` tables, as well as modifications to the migration script to accommodate these changes.

DB: Add tags column to activities table

---

ayon_server/entities/models/fields.py

-   [X] Add traits to representation model
Simple add traits to the model so we can work with them on the lowest level via REST
This is just adding traits to the model, dict of traits (dict of dicts).

Add traits field to representation model

---

api/addons/install.py
ayon_server/api/files.py
ayon_server/files/s3.py
ayon_server/helpers/statistics.py
ayon_server/metrics/__init__.py
ayon_server/metrics/traffic.py
maintenance/tasks/push_metrics.py
schemas/schema.public.sql

Keep track of upload/download in a simple time serie

Traffic statistics

---

api/thumbnails/thumbnails.py
ayon_server/helpers/thumbnails.py

This pull request refactors the thumbnail storage functionality by moving the `store_thumbnail` function from `api/thumbnails/thumbnails.py` to `ayon_server/helpers/thumbnails.py`. Additionally, it simplifies the import statements and updates the relevant function calls to use the new location of `store_thumbnail`.

Server API for thumbnail uploads

---

LICENSE

Reflect upcoming license changes announced here https://ynput.io/blog/ayon-server-is-adopting-fair-source/

License change from Apache 2.0 to FSL-1.1-ALv2

---

api/attributes/attributes.py
api/attributes/models.py
api/attributes/validator.py
ayon_server/entities/models/generator.py

* Added a new `validate_attribute_data` function in `validator.py` to validate attribute data by creating a Pydantic model from the attribute data, ensuring constraints are valid. This helps prevent crashes due to invalid attribute data
* Enhanced error handling in `generate_model` function to log errors and exit the program if an invalid attribute definition is encountered. This ensures that the system does not start with invalid configurations.

Add validator to attribute data model

---

api/tasks_folders/tasks_folders.py

along with `filter`, taskFolders endpoint now accepts `search` top level field that works the same as its graphql counterpart.
Filter is now optional, but when not specified, search must be provided - otherwise it would return all folders in the hierarchy

REST: Add text search support to /taskFolders endpoint

---

api/connect/__init__.py
api/folders/folders.py
api/folders/list_folders.py
api/onboarding/onboarding.py
api/system/info.py
api/users/avatar.py
ayon_server/api/authmw.py
ayon_server/api/lifespan.py
ayon_server/api/server.py
ayon_server/graphql/resolvers/tasks.py
ayon_server/helpers/cloud.py
ayon_server/helpers/download.py
ayon_server/helpers/hierarchy_cache.py
ayon_server/helpers/preview.py
ayon_server/helpers/project_list.py
ayon_server/helpers/setup.py
linker/linker.py
nxtools/__init__.py

Performance improvements 

---

api/bundles/bundles.py
api/projects/anatomy.py
api/settings/models.py
api/settings/settings.py
api/settings/settings_addons_list.py
ayon_server/addons/addon.py
ayon_server/addons/settings_caching.py
ayon_server/info.py
ayon_server/lib/postgres.py
ayon_server/utils/__init__.py
ayon_server/utils/request_coalescer.py

* Added `RequestCoalescer` utility to coalesce requests in the `list_bundles` and `get_project_anatomy` endpoints
*  Refactored the `get_all_settings` function to use the `RequestCoalescer` and moved the logic for retrieving addon lists to a new function `get_addon_list_for_settings`
* Introduced `settings_cache` attribute in `BaseServerAddon` class to optimize settings retrieval and utilized the cache in various settings override methods.
* Added `get_addon_list_for_settings` function to encapsulate the logic for retrieving addon lists for settings.

Improved performance of the most used endpoints

---

ayon_server/events/patch.py

This pull request includes several changes to the `build_project_change_events` function in the `ayon_server/events/patch.py` file to improve event handling and payload generation. The changes include adding new project attributes, refactoring the function for better readability, and ensuring payloads are correctly appended.
Event handling improvements:
* Added new project attributes `statuses`, `tags`, `folder_types`, and `task_types` to the `ADDITIONAL_COLUMNS` dictionary for better event tracking.
* Handled special cases for lists of dictionaries (e.g., `task_types`, `folder_types`, `statuses`, `tags`) by removing the `original_name` key from items in `nval`.

Propagate changes to project aux tables to event stream

---

ayon_server/sqlfilter.py

This table outlines the available comparison operators used in the query filter system, including their meaning, SQL translation, and additional notes.
| Operator    | Description                                      | SQL Expression                          |
|-------------|--------------------------------------------------|-----------------------------------------|
| `eq`          | Equal to                                         | column = value                          |
| `ne`          | Not equal to                                     | column != value                         |
| `lt`          | Less than                                        | column < value                          |
| `gt`          | Greater than                                     | column > value …

Streamlined array comparison in SQLFilter

---

api/addons/router.py
api/thumbnails/thumbnails.py
api/users/router.py
ayon_server/api/auth.py
ayon_server/api/logging.py
ayon_server/api/responses.py
ayon_server/api/server.py
ayon_server/api/system.py
ayon_server/logging.py
ayon_server/utils/strings.py

This pull request introduces significant refactoring and enhancements to the FastAPI application, focusing on middleware restructuring, improved logging, and streamlined exception handling. Key changes include the introduction of a new `LoggingMiddleware` for centralized logging and error handling, removal of redundant code, and simplification of route configurations.
* Added `LoggingMiddleware` to centralize logging and exception handling, replacing inline exception handlers for various errors such as `AyonException`, `HTTPException`, and database constraint violations (`ayon_server/api/logging.py`).
* Removed the `AuthMiddleware`-specific logging logic and moved it into the new `LoggingMiddleware` for better separation of concerns (`ayon_server/api/auth.py`).
* Consolidated exception …

New logging middleware

---

api/files/files.py
api/system/__init__.py
api/system/dbimport.py
ayon_server/files/project_file_record.py
ayon_server/files/project_storage.py
ayon_server/files/s3.py
ayon_server/helpers/cloud.py
ayon_server/models/file_info.py
setup/__main__.py
setup/database.py

This pull request introduces several changes, primarily focused on enhancing file handling, adding database import functionality, and improving SQL query structure. Additionally, there are minor updates to default values and code organization.
* Added a new endpoint `get_project_file_info` in `api/files/files.py` to retrieve detailed information about project files, including size, content type, and filename.
* Added a `dbimport` module in `api/system` to support importing database dump files via a new `/dbimport` endpoint. This includes background tasks for processing the import and optional database migration.
* Modified `INSERT INTO` statements in `create_project_file_record` to support `ON CONFLICT` updates for file metadata.
* Updated the `FileInfo` model to provide default values …

Migration tools

---

api/entity_lists/list_items.py
ayon_server/entity_lists/entity_list.py
ayon_server/sqlfilter.py

This pull request introduces changes to improve the handling of item positions in entity lists and removes an unnecessary logging statement. The most significant updates include refactoring position normalization logic, adding flexibility to position updates, and improving the sorting of items after updates.

Fixed list items sorting

---

api/review/listing.py
ayon_server/forms/__init__.py

Reviewable list with version attributes

---

api/config/config.py
api/system/info.py
ayon_server/config/serverconfig.py

This pull request introduces several changes across multiple files to enhance configuration management, improve feature toggling, and update type annotations. The most significant updates include adding a new `ChangelogSettingsModel` to manage changelog visibility, refactoring type annotations for better readability and maintainability, and modifying methods to incorporate the new settings.

Changelog settings

---

api/files/files.py
ayon_server/files/project_storage.py
ayon_server/files/s3.py

This pull request enhances file handling in the project by introducing support for `Content-Type` and `Content-Disposition` headers during file uploads and downloads. These changes improve compatibility with S3 storage and ensure proper handling of file metadata.

Fix: Store content metadata for s3 files

---

ayon_server/graphql/resolvers/entity_list_items.py

This pull request introduces functionality to determine whether entities (`task` or `folder`) have associated reviewables in the `get_entity_list_items` resolver. The changes add SQL Common Table Expressions (CTEs) and columns to support this feature.

GraphQL: Support for hasReviewabes for 'task' and 'folder' items in entity lists
