ayon_server/settings/__init__.py, ayon_server/settings/models.py
Added more common models to settings models. `PathModel` was renamed to `MultiplatformPathModel` and was added variant with paths as list named `MultiplatformPathListModel`. Currently existing `TemplateWorkfileOptions` model is not usable in all cases as most of it's usage should have less attributes thus a `TemplateWorkfileBaseOptions` was implemented too.
=> More common models

ayon_server/settings/models.py
Common path models had attribute `macos` instead of `darwin`. Also changed order of platforms so linux is before mac.
=> Common settings models: Fix name of attribute from 'macos' to 'darwin'

ayon_server/addons/addon.py
Addon by default returns `type` of client code as `"server"` with `"filename"` instead of `http` with `"url"`.
It is easier to know that source of addon client code is from server then receiving url from server (that can potentially lead to wrong server as server may not know the base url correctly).
=> Addons distribution: Change type and content of client zip file

ayon_server/settings/__init__.py, ayon_server/settings/models.py
All host addons must have `imageio` settings which is using the same models so they should be available in common models thus they are added.
Removed few unused models `ContextModel`, `ProfileModel` and `TemplateWorkfileOptions`.
=> Settings: Add default imageio models for hosts

reload.sh, start.sh
Use recommended `/usr/bin/env bash` instead of `/bin/bash` in shell scripts.
This fixes issue on windows launching the scripts in docker.
=> Use universal bash definition

start.sh
Just fixing EOL issue in `start.sh` that was crashing docker container on start - converting from windows to linux EOL.
=> Bug: fix line ends in start.sh

.gitattributes
** Handling end of lines
This is adding `.gitattributes` file to help resovling EOL characters on multiple platforms, mainly because `.sh` file were check out with Windows CR/LF effectively breaking run in the Docker.
=> Add gitattributes to handle EOL

ayon_server/installer/models.py
Added option to use full potential of poetry dependencies structure by allowing nested dictionary as value of pacakge.
We use git repositories in python modules which are defined as `{"git": "<url>", "branch": "<branch>"}`. There are more options what can be inside.
=> Support nested data in python modules

setup/attributes.py
The attribute on version should be named families and not product types.
I do expect this will require more changes, but this is must have change.
=> Change 'Product types' to 'Families' attribute on version

api/resolve/__init__.py
When path was resolved for entity, it wasn't properly treated by platform determined with site id - forward slashes vs. backward slashes. Also, when the `{hierarchy}` key was empty for example, it produced path with double slashes:
template:
```
{root[work]}/{project[name]}/{hierarchy}/{folder}
```
with empty `hierarchy` key resulted for example in
```
C:/projects/CoolProject//SomeFolder
```
now it will return
```
C:\projects\CoolProject\SomeFolder
```
=> Resolve: deal with platform specific paths and empty template keys

api/attributes/attributes.py, api/system/info.py, ayon_server/entities/models/__init__.py, ayon_server/entities/models/generator.py, ayon_server/settings/postprocess.py, ayon_server/types.py
enumerator on `string` and `list_of_strings` attribute types are not enforced by model validators and they are mostly informative (to create dropdowns in UX), so it is not crucial to restart the server when an enumerator list changes.
In this PR, postprocess_settings_schema is modified, so anatomy model always load the enumerator from the database instead of using locally loaded `EntityModel.model.attrib_model`. The same is applied to `/api/info` request, so initial list of attributes return updated enumerators instead of cached ones. 
To get the current enumerator it is possible just to reload the page instead restarting the server. This applies only for enumerators. Other attribute settings have a direct impact on their Pydantic model and REST API, so the restart is necessary.
=> Enhancement / Use dynamic resolver for attribute enumerators

api/system/info.py, ayon_server/__init__.py
`/api/info` endpoints now provides information on branches and commits the image was created from. Pushing the information there is a responsibility of CI. Information is taken from `/backend/RELEASE` file, which is structured as follows:
```
version=0.5.2
build_date=20231013
build_time=1108
frontend_branch=develop
backend_branch=enhancement/return_release_info
frontend_commit=30409b9
backend_commit=b86bc7e
```
`releaseInfo` field in `api/info` is nullable and is null when the file is not available (for example when running from a locally mounted copy of the backend repository.
=> Provide detailed release information in /api/info

ayon_server/api/server.py, ayon_server/auth/password.py, ayon_server/config.py, ayon_server/lib/redis.py
Implementation of brute force protection of `/api/auth/login` endpoint. Disallows login for IP addresses which attempted to log in with a wrong password more than `ayonconfig.max_failed_login_attempts = 10` for next `ayonconfig.failed_login_ban_time = 600` seconds.
=> Brute force protection

api/projects/projects.py, ayon_server/entities/core/projectlevel.py, ayon_server/graphql/dataloaders/__init__.py, ayon_server/graphql/nodes/event.py, ayon_server/graphql/nodes/folder.py, ayon_server/graphql/nodes/product.py, ayon_server/graphql/nodes/project.py, ayon_server/graphql/nodes/representation.py, ayon_server/graphql/nodes/task.py, ayon_server/graphql/nodes/version.py, ayon_server/graphql/nodes/workfile.py, ayon_server/graphql/resolvers/events.py, ayon_server/graphql/resolvers/folders.py, ayon_server/graphql/resolvers/projects.py
`data` field can be queried using GraphQL and it is returned as a stringified JSON. it is also now available to normal users via rest for reading. 
Storing data is still reserved for managers+ and custom addon endpoints. Limiting data access similarly to attribute whitelist is not yet implemented (nor needed).
=> Project level data accessible via GraphQL. 

setup/__main__.py
Providing settings template was only possible using stdin, now the setup script attempts to load the template from well-known `/template.json` file as well, so it possible to provide basic settings using a mounted volume.
=> Add an option to load settings template from a mounted file

api/bundles/bundles.py, ayon_server/addons/addon.py, ayon_server/addons/definition.py
Addons have a `system` attribute - until now, we used this attribute only to hide it from the interface for guests. This PR repurposes this attribute so now, when an addon with `system=True` set is mandatory in bundles.
`[PUT] /api/bundles` does now allow creating a bundle without system addons included  - this is especially useful for authentication addons where not including it to a production bundle prevents users to log in, but it could be used for the core addon, subscriptions etc.
This does not ensure the addon is in the latest version - this should still be the responsibility of the administrator.
=> System addons mandatory in bundles

api/addons/project_settings.py, api/addons/site_settings.py, api/addons/studio_settings.py, ayon_server/settings/enum.py, ayon_server/settings/postprocess.py
Enum resolvers now can accept source addon itself and use its own settings
```python
async def recursive_enum_resolver(
addon: "BaseServerAddon",
settings_variant: str = "production",
project_name: str | None = None,
) -> list[str]:
if addon is None:
return []
if project_name:
settings = await addon.get_project_settings(project_name=project_name, variant=settings_variant)
else:
settings = await addon.get_studio_settings(variant=settings_variant)
return settings.list_of_strings
```
Additionally resolvers accept `settings_variant` field (defaults to production, requires the latest develop frontend ) and built-in `folder_types_enum` and `task_types_enum` now return folder/task types from the primary anatomy preset, when invoked from studio settings.
=> More options for settings enum resolvers

api/thumbnails/thumbnails.py, ayon_server/entities/models/fields.py, ayon_server/entities/task.py, ayon_server/graphql/dataloaders/__init__.py, ayon_server/graphql/nodes/task.py, ayon_server/graphql/resolvers/tasks.py, schemas/schema.project.sql, schemas/schema.public.update.sql
Add thumbnails support for tasks using the same mechanism as in folders, versions and workfiles.
Setup automatically adds thumbnail_id column to all existing projects if it does not exist, so this update does not break anything.
Testing:
- Switching to this version should run the update script when container starts, which adds the thumbnail_id column. You can check that using `SELECT thumbnail_id FROM  project_PROJECTNAME.tasks;`
- It also exposes task.thumbnailId property in graphql and rest. If something is wrong, would break.
=> Task thumbnails

api/resolve/__init__.py
Entities item now contains `target` field, which specifies the deepest entity type specified in the URI.
This may be used to determine, what was selected without prior knowledge of the data model.
```json
[
{
"uri": "ayon://demo_Commercial/assets/environments/00_sqionguoks?product=setdressMain&version=v004",
"entities": [
{
"projectName": "demo_Commercial",
"folderId": "b0790c9e4c9911eeb6d40242ac140004",
"productId": "b07a1ba24c9911eeb6d40242ac140004",
"versionId": "b07ad3ee4c9911eeb6d40242ac140004",
"target": "version"
}
]
}
]
```
=> Return target entity type on entities resolved from URI

api/bundles/bundles.py, ayon_server/addons/definition.py
system addons must be present in all bundles. Previously an error was raised if an addon was not provided, which didn't work with re-bootstrapping properly. So now we add the latest version of the addon automatically.
=> Auto add system addons to bundles

ayon_server/graphql/resolvers/products.py, setup/__main__.py
GraphQL products resolver now support nameEx and pathEx arguments to filter the results by product name or the parent folder path regular expressions.
=> Regex filters for graphql products resolver

api/settings/settings.py
Addons with broken settings (for example because of incompatible model) are now listed in settings addon list in red (similarly to unloaded addons), so it is possible to use low-level settings editor to repair them. /api/settings also provide a full traceback in that case (to display it in the UX)
=> Display addons with broken settings in the addon list

api/links/links.py, ayon_server/graphql/nodes/common.py, ayon_server/graphql/resolvers/links.py, ayon_server/graphql/resolvers/versions.py, linker/__main__.py, linker/linker.py, schemas/schema.project.sql, schemas/schema.public.update.sql
link table is changed to contain a custom `name` field.
The name is nullable and it may be used to use an integration-specific identifier. Links of the same type no longer need to be unique.
On the database level, the following has changed:
- Renamed `link_name`  to `link_type`
- Added `name`  column 
- Moving `author`  from `data` to its own column
- Remove `link_unique_IDX` 
API-wise, this PR should be 100% backward compatible, but `link` field in `[POST] /api/{project_name}/links` is now deprecated. Instead, please use `link_type` (for now, both may be used).
Graphql and rest both expose new optional `name` field.
This PR is now in `ayon:experimental` image. In order to migrate existing projects to the new schema, the container must start (reloading only won't trigger the migration …
=> Custom link names

api/bundles/bundles.py, ayon_server/api/postgres_exceptions.py, ayon_server/api/server.py, ayon_server/entities/core/projectlevel.py, ayon_server/entities/folder.py, ayon_server/entities/project.py
Added exception handler for Postgresql exceptions, so catching them in the endpoints is no longer needed (when the request should fail). Handler does its best to format the exception to human-readable description returned in response detail.
This should avoid passing cryptic unhandled postgres to users.
=> Handle postgres exceptions directly

api/addons/__init__.py, api/bundles/bundles.py, api/services/services.py, ayon_server/addons/addon.py, ayon_server/addons/definition.py
New addon type attribute defines, whether the addon has ('server') or does not have ('pipeline') a client part. As for 1.0.4, this will only be used to allow changing the addon version in an existing bundle. In the future a dedicated 'server' bundle independent from pipeline will be introduced to simplify updating server-only addons without touching the pipeline part.
=> Addon type attribute

ayon_server/addons/addon.py, ayon_server/settings/common.py, pyproject.toml
In 1.0.5 migrate_settings script was not able to convert settings with field without default value set.
This fix uses addon settings defaults (from get_default_settings) in this case, so migration won't fail.
How to test:
do basically any change in maya addon and try to copy the settings to a different version
=> Map default values to new model data during migration

api/system/__init__.py, ayon_server/api/server.py, ayon_server/api/system.py, ayon_server/events/base.py
We're introducing a couple of new API endpoints to help us keep tabs on when our server needs a bit of a time-out (a restart, that is). 
**Checking if a Restart is Needed**
`[GET] /api/system/restartRequired` 
```
{
"required" : true,
"reason": "Server needs to be restarted because of something"
}
```
This endpoint is your go-to for finding out if the server is signaling for a restart. It answers a simple question: "Does our server need to reboot?" and if so, "Why?" 
The frontend should check this endpoint and if `required` is true, display a banner to administrators with a button triggering the actual restart.
To reduce the latency, administrators could also listen for `server.restart_required` topic in the WS event stream. In that case, the reason for restarting is in the 'description' …
=> Server-side restart_required handler

ayon_server/api/postgres_exceptions.py, ayon_server/api/server.py, ayon_server/api/static.py
Instead of using mount created during server startup, addon static content (public, private and frontend directories) is now served using routes. This significantly reduces the amount of routes in the application (from up to 3 per addon to just 3).
This approach also fixes the problem mounts cannot contain `+` sign in path names. since addon versions CAN contain `+` (as it is a valid semver character). this was an issue. API routes with dynamic paths work.
It is a drop-in replacement of the original functionality, but it would be nice to check whether everything works (downloading client zip files for example)
=> Replaced StaticFile mounts for addon static content with routes

api/access_groups/access_groups.py, ayon_server/access/access_groups.py, ayon_server/access/permissions.py
This fixes settings editor schema for permissions. Folder access role is now enum as well as attribute list.
=> Fix permission schema postprocessing

api/addons/project_settings.py, api/addons/router.py, api/addons/studio_settings.py, api/system/info.py, ayon_server/addons/addon.py
Adds a "on_settings_changed" hook to BaseServerAddon class, which is triggered, when the settings of the addon are changed. This is useful for addons that need to react to settings changes.
on_settings_changed method, accepts old_settings and new_settings arguments, as well as optional variant, project_name, site_id and user_name when applicable.
=> Added addon on_settings_changed hook

api/folders/__init__.py, api/folders/folders.py, api/folders/list_folders.py, api/folders/router.py, api/hierarchy/hierarchy.py, ayon_server/entities/folder.py, ayon_server/helpers/hierarchy_cache.py
Added a new endpoint `[GET] /api/projects/{project_name}/folders` which returns all folders in a project.
This endpoint is heavily optimized for performance and should replace `hierarchy` endpoint and several GraphQL queries
from the editor. 
Folder data is stored in Redis cache and recached when a folder is created, updated or deleted.
The endpoint itself only handles retrieving from the cache and ACL checks. 
With 10 000 folders in the project, data loading takes ~10ms. The biggest bottleneck is HTTP request/response time.
But the main goal is not to have blazing fast response times, but to reduce the number of queries to the database.
Using a boolean query argument `attrib` it is possible to query attributes (including ownAttrib list) as well.
=> Folder list endpoint

.gitignore, ayon_server/auth/session.py, ayon_server/config.py
When client real IP changes constantly, due the connection via mobile internet for example, sessions can often be invalid.
Added the probability to skip checking the session IP matches the real IP via config.
=> feat: disable check session ip by config

api/anatomy/__init__.py, ayon_server/settings/enum.py
Instead of the original `_` magic value, anatomy presets may be queried using `__primary__` and `__builtin__` 
original `_` is now alias to `__builtin__` to maintain backward compatibility.
Enum resolver for settings is available so it is possible to create fields such as:
```python
anatomy_preset: str = Field(
"__primary__",
title="Anatomy preset",
description="Anatomy preset to use",
enum_resolver=anatomy_presets_enum,
)
```
in that case, settings value will always point to the primary preset. 
If no primary preset is defined, it will point to the built-in.
User may then override the value with a an explicit preset name.
=> added __primary__ and __builtin__ anatomy presets

ayon_server/activities/update_activity.py
In the future, this should be replace with edit history.
=> Allow patching activities created by someone else, but log it

ayon_server/activities/event_hook.py, ayon_server/activities/models.py, ayon_server/graphql/nodes/activity.py
Creating a new version now propagates to activity feed. activityData.context contains additional information to construct the message body.
=> Propagate publishes to activity feed

api/bundles/actions.py, api/bundles/bundles.py
Adds bundle.status_changed event which is triggered whenever a bundle is set to production or staging or achieved. Details on the new state are available in the event summary.
=> Added bundle.status_changed event

schemas/schema.project.sql, schemas/schema.public.sql, schemas/schema.public.update.sql
Adds more (very needed) database indices to tables related to events and activity feed. This may cause slower server update when used for the first time as indices need to be created on existing data, but preliminary tests suggest it should take a few seconds.
=> Add more db indices

ayon_server/graphql/resolvers/common.py, ayon_server/graphql/resolvers/tasks.py
In order to select exported attributes from the parent query, task resolver now looks for any field ending with `attrib` instead of explicit `attrib` field, which is not present when a fragment is used
=> fix: support inherited attributes in fragments

api/bundles/check_bundle.py, ayon_server/addons/addon.py
Addons may now provide `ayon_soft_required_addons` field, which specifies addons, which MUST be in the given version, if the addon is in a bundle. It is similar to `ayon_compatible_addons` with the difference this returns error instead of warning when the condition is not met.
=> Add support for ayon_soft_required_addons

api/addons/project_settings.py, api/addons/studio_settings.py, ayon_server/addons/addon.py, ayon_server/settings/common.py, ayon_server/settings/overrides.py, ayon_server/utils.py
-   [x] Referenced issue is linked
`migrate_settings` function in `BaseServerAddon.convert_settings_overrides` is replaced by `migrate_settings_overrides`.
The new function does not return BaseSettingsModel which needs to be postprocessed, rather it returns a dict, so input and output have the same format and it makes it possible to know which values actually have overrides.
The new function drops the original custom_conversions functionality as it was overengineered and not used.
Additionally, modify_settings endpoints now accept `__pinned_fields__` list, that enables explicit pinning of default values via settings editor (without pin_override function).
=> Migrate settings rewrite

api/projects/roots.py, ayon_server/helpers/roots.py
-   [x] Referenced issue is linked
When using `api/projects/{project_name}/roots` endpoint (GET/PUT), empty values (nulls or empty strings)
are no longer returned. When no override is present, exclude that root (or site) from the result.
=> Do not return empty site root overrides

api/addons/install.py
Fixes incorrect summary (addon_name and addon_version) coming from the event stream to get_installed_addon_list endpoint
=> Addons: fix incorrect summary parsing in get_installed_addon_list

setup/access_groups.py, setup/users.py
It is now possible to ensure access groups are created during setup.
Access groups are defined in template.json file as follows
```json
"accessGroups": [
{
"name": "publisher",
"forceUpdate": false,
"data": {
"read": { "enabled": false, "access_list": [] },
"create": { "enabled": true, "access_list": [] },
"delete": { "enabled": true, "access_list": [] },
"update": { "enabled": true, "access_list": [] },
"publish": {
"enabled": true,
"access_list": [{ "path": null, "access_type": "assigned" }]
},
"endpoints": { "enabled": false, "endpoints": [] },
"attrib_read": { "enabled": false, "attributes": [] },
"attrib_write": { "enabled": false, "attributes": [] }
}
}
]
```
- `data` field follows accessGroup model as specified in REST API,
- `forceUpdate` flag ensures existing accessGroup is …
=> Setup: support for bootstrapping access groups

ayon_server/settings/common.py
Fixes setting migration when overrides are on list of submodels.
`migrate_settings_overrides` now check whether a field is a list of submodels and in that case,
iterate over all elements and parses them individually.
see the linked issue
=> Settings: fix copying deeply nested lists of submodels

ayon_server/activities/event_hook.py
Event hook creating activities when assignee list changes now resolves user full names
and populates the activity body with a correct link.
=> Resolve user full names in assignee changed event hook

api/addons/project_settings.py, api/addons/site_settings.py, api/projects/roots.py, api/resolve/__init__.py, api/settings/settings.py, ayon_server/api/dependencies.py
This PR unifies site_id dependency across rest endpoints. Two dependencies `SiteID` and `ClientSiteID` are used as specified in the linked issue.
Endpoints `/api/projects/{project_name}/roots/{root_name}` still use site_id provided in path. This is inconsistent, but probably not worthed breaking the backwards compatibility.
`/api/settings` still expect site id to be provided as a query argument. Should it also accept header option as it is called from the client application and site_id is by default sent with the request? or do we need granularity here and option to get just project settings? @iLLiCiTiT 
- Save project site settings and ensure they are correctly stored when different sites are used
- Save different site overrides for project roots
- Ensure site overrides for settings and …
=> REST API: Unify SiteID specifications 

ayon_server/addons/library.py
`AddonLibrary` has api functions to get addons by variant, not just `"production"` and `"staging"` but dev bundles too.
Modified `get_active_versions` to also collect addon versions for dev bundles. Implemented helper methods `get_addon_versions_by_variant`, `get_addons_by_variant` and `get_addon_by_variant` as api functions. Function `get_addon_by_variant` is also used by `get_production_addon` and `get_staging_addon`.
=> Addons library: More api options to receive addons

ayon_server/activities/create_activity.py, ayon_server/api/messaging.py, ayon_server/events/eventstream.py
When a new activity is created, referenced users are notified using fire and forget websocket event with `inbox.message` topic.
The event uses the first line of the message body as its description `summary.isImportant` flag could be used to silence unimportant messages based on the user preferences.
=> Inbox: Websocket notification

ayon_server/graphql/__init__.py, ayon_server/graphql/resolvers/users.py
Fixes: https://github.com/ynput/ayon-backend/issues/236
It is no longer possible to list users from project that you are not assigned to.
Additionally, a status code from AyonException is passed to graphql error extensions.
=> Disallow listing users from unassigned projects

api/resolve/__init__.py, api/uris/__init__.py, api/uris/queries.py, api/uris/router.py, api/uris/uris.py
Implements `[POST] /api/projects/{projectName}/uris` endpoint, which returns a list of AYON URIs for a given list of Entity IDs.
Entity IDs must be of the same entity type and belong to the same project. 
Any assignee to the project can resolve URIs.
Request payload is a JSON with the following fields:
Enum: `folder` `product` `version` `representation` `task` `workfile`
Array of strings (Entity IDs) - entity ID may, but does not need to be hyphenated
So a request like:
```json
{
"entityType": "representation",
"ids": ["40680ada-fcbc-11ee-9ea5-0242ac140004"]
}
```
Returns:
```json
{
"uris": [
{
"id": "40680adafcbc11ee9ea50242ac140004",
"uri": "ayon+entity://demo_Commercial/shots/sh010&product=workfileCompositing&version=v001&representation=ma"
}
]
}
```
=> REST: Entity IDs to URIs endpoint

ayon_server/api/dependencies.py, ayon_server/api/metadata.py, ayon_server/api/server.py, ayon_server/config.py
This PR introduces changes to the way we use OpenAPI schema for generating TypeScript definitions.
Addon endpoints, which are primarily relevant for addon developers, will now be excluded from the schema by default.
These endpoints can be included by setting the `ayon_openapi_include_addon_endpoints` environment variable.
This change reduces unnecessary noise in the schema and improves clarity for the majority of users.
Shared authorization options, which are repeated across all endpoints, are now excluded from the schema.
Instead, authorization methods are comprehensively described in the Authorization section of the REST documentation. This avoids redundancy and centralizes authorization information for easier maintenance and reference.
Excluding addon endpoints by default enhances …
=> Exclude addon endpoints and auth headers from openapi

ayon_server/api/messaging.py, ayon_server/auth/session.py
Users who aren't assigned to a project no longer receive project-related events.
=> Websocket: do not send project events to users without a role

api/activities/activity.py, ayon_server/activities/create_activity.py, ayon_server/activities/delete_activity.py, ayon_server/activities/update_activity.py
When an activity is created RT `activity.created` event is dispatched with a list of all affected entities. that should trigger cache invalidation of the activity feed.
Keep in mind, that sender matching will prevent originating browser tab receiving the message, so whoever creates the activity is responsible to invalidate their own cache. 
Don't forget subscribing to `activity.created` topic.
(the same structure is used for `activity.updated` and `activity.deleted` topics
=> Activity feed: notify clients when an activity is created, updated or deleted

api/review/__init__.py, api/review/listing.py, api/review/patching.py, api/review/sorting.py, ayon_server/api/dependencies.py
Adds patch endpoints for sorting and relabeling reviewables
=> Reviewables sorting and patching

api/events/enroll.py, api/resolve/__init__.py
Similarly to the check in `/api/resolve` enpoint, `/api/enroll` now returns `503` status when the database pool is overloaded. 
This signals connected services, that enroll is not available at the moment and they should try it later. 
Since evaluating this status has no overhead, it can be handled the same way as "no response" / "nothing to do". 
Reason: In the case DB is overloaded, `enroll` endpoint is the one that "can wait" and let a few connection in the pool available for UI.
=> Disable enroll when db pool is getting full

api/auth/sessions.py
Allow creating additional sessions for users using `[POST] /api/auth/sessions`
- services can create sessions for any users
- normal users can create sessions only for themselves
=> Authentication: create_session endpoint

ayon_server/settings/__init__.py, ayon_server/settings/anatomy/__init__.py, ayon_server/settings/anatomy/folder_types.py, ayon_server/settings/anatomy/link_types.py, ayon_server/settings/anatomy/roots.py, ayon_server/settings/anatomy/statuses.py, ayon_server/settings/anatomy/tags.py, ayon_server/settings/anatomy/task_types.py, ayon_server/settings/anatomy/templates.py, ayon_server/settings/models.py, ayon_server/settings/settings_field.py
`SettingsField` is no longer just an alias to `pydantic.Field` but reimplements it and provides type checking for all additional types used in settings. **kwargs is now used just for backward compatibility (preventing raising errors, instead it logs a message about unsupported argument passed)
=> Settings: Improved SettingsField

api/events/__init__.py, api/events/enroll.py, api/events/operations.py, ayon_server/events/enroll.py, ayon_server/sqlfilter.py
Enroll now accepts source topics both as strings with `*` wildcard or a list of strings. 
That maintains 100% backwards compatibility while allowing multiple topics selection without using expensive wildcards.
Additionally, this PR adds a new endpoint for batch updates of events. It was implemented in order to make the API testable, so it is just a minimal implementation only supporting event deletion, but it will be expanded later.
=> Events: allow specifying source topics in list in enroll + batch event delete

api/desktop/deps.py, api/desktop/installers.py
Original download link is stored in dependency packages and launcher manifests. Since these links expire, we need to filter them out to prevent downloading from dead links. 
This is a hot fix and eventually, the links should also be removed when the manifest is stored.
=> Remove download.ynput.cloud links from launcher and dependency packages sources

setup/access_groups.py
Provide a sane default access groups when the server is started for the first time and there are no explicit groups set in template.json
Has unrestricted access to the project
Has unrestricted read/publish access to the project, but cannot change the project hierarchy
Can read/publish the parts of the hierarchy where they have tasks assigned
=> Setup: Default access groups

ayon_server/graphql/resolvers/tasks.py
added `includeFolderChildren` to the tasks resolver, that expands the resultset with tasks under all children folders when `folderIds` list argument is used
=> GraphQL: Querying tasks in nested folders

api/files/files.py, api/files/video.py, ayon_server/helpers/ffprobe.py
A majority of browsers can playback QuickTime files directly, so this PR allows the playback of QT reviewables without transcoding. Transcoding is still recommended and supported as QT flavors may vary and playback may be unsupported on some platforms.
=> Allow QuickTime files as proxies

api/uris/queries.py
-   [ ] Referenced issue is linked
Fixes the returned entity URIs for representation entity type.
When resolving the current URIs fail.
This fails:
```
ayon+entity://ayontest/asset/char_hero&product=usdMain&version=v032&representation=usd
```
This works:
```
ayon+entity://ayontest/asset/char_hero?product=usdMain&version=v032&representation=usd
```
It's the `&`. Lacking a question mark.
=> Fix returned entity URIs for representation entity type

ayon_server/api/frontend.py, ayon_server/api/server.py
Introduces a custom frontend staticfiles handler, that does not use cache-control for index.html, instead it keeps the content of index.html in memory cache. 
Index file is small so we can safely keep it in memory and serve it every time user reloads the page. Contents is loaded from the disk every time server is restarted, which should cover changes in imports.
=> Frontend index caching

api/activities/__init__.py, api/activities/activity.py, api/activities/reactions.py, ayon_server/graphql/nodes/activity.py
New endpoint `[POST] /api/projects/{project_name}/activities/{activity_id}/reactions` with the payload of:
```json
"reaction": "like"
```
New endpoint `[DELETE] /api/projects/{project_name}/activities/{activity_id}/reactions/{reaction}`
where {reaction} is a previously created reaction
Graphql sub-node on each activity `reactions` with the following structure:
=> Activity feed:  Reactions

ayon_server/graphql/resolvers/representations.py
If there is an ACL with the type - "Assigned", and there are tasks assigned to the user, there will be the "column reference id is ambiguous" exception when querying representations.
=> fix: column reference "id" is ambiguous

ayon_server/api/dependencies.py
`CurrentUser` dependency returned 401 error when user tried to access a project without permission. 401 error triggers redirection to the login page in the frontend without clearing the stored access token, which leaded to infinite loop of pare reloads. The dependency now returns 403, that makes more sense (as it it a permission error, not authorization) and fixes this issue.
=> Auth: Infinite loop when accessing unassigned project

api/resolve/__init__.py, api/resolve/models.py
When a provided URI is malformed or does not make sense, return "error" field with the problem description instead of empty entity list.
When a URI issue is recoverable (such as "cAsEiNsEnSiTiVe" version name), attempt to fix the problem
```json
[
{
"uri": "ayon+entity://ayontest/asset/char_hero?product=usdAsset&version=v00000021&representation=usd",
"entities": [
{
"projectName": "ayontest",
"folderId": "ac991b60b4cb11eeb7fc7730318c5a70",
"productId": "506507b5ec8b11ee86565feb1905149c",
"versionId": "d21458da394211ef8d7e0b740ae1b9fa",
"representationId": "d21ee02e394211ef8c180b740ae1b9fa",
"filePath": "{root[work]}/ayontest/asset/char_hero/publish/usd/usdAsset/v021/ynts_char_hero_usdAsset_v021.usd",
"target": "representation"
}
]
},
{
"uri": …
```
=> Resolver: Handle malformed URIs and provide error messages

api/thumbnails/thumbnails.py, ayon_server/background/clean_up.py, ayon_server/files/project_storage.py, ayon_server/files/s3.py, ayon_server/helpers/thumbnails.py, schemas/schema.project.sql, schemas/schema.public.update.sql
This pull request introduces several enhancements and new functionalities to the thumbnail storage and retrieval system. The most important changes include adding support for original thumbnails, refactoring storage methods, and improving the cleanup process for unused thumbnails.
When an uploaded thumbnail is larger than a defined value (currently hardcoded 600px both width and height) the original is stored in the project storage (server/projects/{project_name}/thumbnails) and a scaled down version is saved to the DB for quick retrieval.
- Added an `original` parameter to various thumbnail retrieval functions to fetch the original image from storage if available. 
- Introduced new methods in `ProjectStorage` for handling thumbnails, including storing, retrieving, and deleting thumbnail …
=> Optimize entity thumbnail storage

ayon_server/settings/anatomy/templates.py
-   [ ] This comment contains a description of changes
-   [ ] Referenced issue is linked : https://github.com/ynput/ayon-unreal/issues/64 and  https://github.com/ynput/ayon-unreal/issues/66
Added the published template setting for unreal uasset/umap publishing 
Related to this PR: https://github.com/ynput/ayon-core/pull/859
The current uasset/umap publisher is using default template name as the published path, but the default one would change the filename of the uasset/umap, which would corrupt the uasset/umap, and u sers cannot load the uasset/umap. There is some custom publish template needs to be added to make sure the uasset is published with original filename so that the file itself would not be corrupted.
The related ayon-core PR: https://github.com/ynput/ayon-core/pull/859
The …
=> Add unrealuasset as the publish template

api/projects/projects.py, ayon_server/files/project_storage.py, ayon_server/helpers/download.py, ayon_server/helpers/project_list.py
https://github.com/ynput/ayon-backend/issues/380
Upon project deletion, the project directory is renamed to `{project_name}.{timestamp}.trash` 
Since project names cannot contain `.` character, dot-delimination is non ambiguous, using a timestamp ( `int(time.time()`) allows multiple versions of the same project and restore the snapshot. 
Sufffixing the projectname with `.trash` makes it easy to filter & delete.
> [!IMPORTANT] 
> This approach ensures 100% backward compatibility with existing projects
S3 does not support "directory" renaming so we need a different approach here:
- every project storage from now uses `{project_name}.{timestamp}` as the project root. where the timestamp is the project `created_at`, so it's deterministic, can be paired with the current version of the project …
=> Project files: Trashing project files directories upon deletion

ayon_server/helpers/deploy_project.py
Optimized assigning users to new projects - if there's a lot of normal users in the studio with default access groups set, this speed up is significant. 
Inactive users are also no longer added automatically to new projects.
=> Projects: speed up project deployment

ayon_server/background/clean_up.py
We could just assume project is marked as inactive when there's no ongoing activity that should be cleaned-up
=> Skip inactive-projects clean-up

ayon_server/activities/event_hook.py, ayon_server/activities/watchers/set_watchers.py, ayon_server/graphql/resolvers/inbox.py, schemas/schema.public.sql
When watching a task:
- User gets added as a watcher to all versions of that task automatically.
- User gets added to any new versions of that tasks automatically.
When unwatching a task:
- User gets removed from watching all task versions.
- User does not get automatically added to new task versions.
Setting/unsetting a watcher should invalidate client cache as now the new state is only visible after page reload
Status changes are no loner considered important in the inbox, regardless user watching the entity or not
`get_user_inbox` query now takes in account whether the user has access to the project. If they're unassigned from the project, related items will disappear from the inbox (that also improves the performance).
=> Watching and inbox rules improvements

ayon_server/entities/models/generator.py
This pull request includes a small but important change to the `generate_model` method in the `ayon_server/entities/models/generator.py` file. The change ensures that if the `enum` field contains instances of `AttributeEnumItem`, their values are extracted correctly.
=> Fix attribute model for enums

api/events/enroll.py
This pull request includes a small but important change to the enroll endpoint. The change ensures that an `EmptyResponse` is returned if the cached result is not available.
=> Handle empty response when returning cached 'nothing to do' from enroll

ayon_server/activities/references.py
When creating an activity on a task, create an additional reference to the task folder
=> Added folder reference to task activities

ayon_server/background/clean_up.py
Refactored activity clean-up query, that caused timeouts in the clean-up process. Now it should not. 
- BACKUP!!!!!!
- Start ayon
- Wait a couple of minutes
- Validate that activities of existing entities weren't deleted
clean-up does not touch activities that were updated or their parent entities were deleted in last 10 days. 
You may therefore:
- Find an entity with 10 days or older comment
- Delete that entity
- Delete related `entity.xxxxx.deleted` event from the events table
- Restart the server and wait a couple of minutes
- In the server log, you should see `Deleted {count} orphaned activities from {project_name}`
=> Optimized activity clean-up query

ayon_server/events/patch.py
Additional events are triggered when a top-level field of an entity is changed:
```python
{
"parent_id": "parent_changed",  # for folders
"folder_id": "folder_changed",  # for tasks and products
"task_id": "task_changed",  # for workfiles and versions
"product_id": "product_changed",  # for versions
"version_id": "version_changed",  # for representations
}
```
Keep in mind that there are constraints in the API, that for example forbids changing hierarchy of folders (e.g. changing parent_id of a folder) when there's a published version in that folder.
=> Trigger event when entity parent changes

ayon_server/graphql/resolvers/activities.py
Querying activities by type implemented as an extension of the existing GraphQL resolver.
It is now possible to filter activities from a given time range using `changedBefore` and `changedAfter` params
=> GraphQL: Add changedBefore and changedAfter args for activities resolver

ayon_server/metrics/projects.py, ayon_server/metrics/system.py
Include original thumbnails off-loaded to the project storage in storage utilization metrics
=> Include thumbnails in storage usage metrics

ayon_server/events/eventstream.py
`EventStream.subscribe()` now returns a string token, that could be used for unsubscribing later on.
This is useful in the cases an addon needs to listen for events only if it is in production for example:
```python
async def setup(self):
self.event_tokens = []
await self.on_bundle_updated() 
EventStream.subscribe("bundle.updated", self.on_bundle_updated)
async def on_bundle_updated(self, _: EventModel | None = None) -> None:
if await self.is_production():
if not self.event_tokens:
logging.debug(f"{self} is in production mode, subscribing to events")
self.event_tokens = [
EventStream.subscribe("entity.folder.status_changed", self.on_status_changed),
EventStream.subscribe("entity.task.status_changed", self.on_status_changed),
]
else:
if self.event_tokens:
logging.debug(f"{self} is not in …
```
=> Events: Unsubscribe from event stream

ayon_server/auth/session.py, ayon_server/config/ayonconfig.py
This pull request includes changes to the session management and configuration in the `ayon_server` module. The most important changes involve updating the session lifetime logic and modifying the default session TTL configuration.
- Updated the logic to extend the session lifetime only if the remaining TTL is less than the TTL minus 120 seconds. This change ensures that the session is updated more efficiently.
- Changed the default session TTL from 24 hours to 72 hours to provide a longer session lifetime by default (hold session over the weekend)
=> Auth: fixed session invalidation logic

api/tasks/tasks.py, ayon_server/events/patch.py
This pull request includes changes to improve the handling of task assignees and event dispatching in the `[POST] task/assign` endpoint.
* Ensured the `entity.task.assignees_changed` event is dispatched with the appropriate payload when assignees are changed
* Converted `assignees` to a set to avoid duplicates and improve performance. Added a check to return early if there are no changes to assignees.
* Added an audit trail to track changes in task assignees by including the old and new values in the event payload.
=> Added missing event to task/assign endpoint

api/files/files.py, ayon_server/helpers/preview.py
use `[GET] /api/projects/{project_name}/files/{file_id}/still?t={timestamp}` to get a still frame from a video file.
Timestamp must be specified as float (seconds).
Returns 404 when the requested file is not found or timestamp is out of range
=> Files: Grabbing still frames from videos

api/system/info.py, ayon_server/entities/models/fields.py
Removes login page-related information from /api/info by default. To include ssoOptions and page customizations, add `?full=true`
Response for authenticated request to this endpoint does not change at all. This PR prevents unnecessary calls to the backend when performing health checks.
=> API: lightweight /api/info request

api/activities/activity.py, ayon_server/activities/update_activity.py
This pull request includes changes to the `api/activities/activity.py` and `ayon_server/activities/update_activity.py` files to enhance the activity editing functionality. The changes allow administrators to edit any activity, users to edit their own activities, and ensure non-owners can only modify checkboxes in comments.
=> Allow all users to update checkboxes in comments

ayon_server/addons/library.py, ayon_server/api/messaging.py, ayon_server/events/eventstream.py
This pull request introduces several key improvements to the handling of event subscribers and the organization of hooks in the EventStream class.
When an event is created and a subscriber is attached to the topic, the function is triggered only on the current server instance.
Use Case: Situations where the event should be processed once, e.g., "Entity status change sends a notification."
In scaled deployments of Ayon (multiple server instances), some events need to trigger functions on all instances.
Use Case: "Addon settings change requires all addon instances to reload their cache."
Added a new parameter, `all_nodes: bool`, to the `EventStream.subscribe method` (Default: False)
When set to True, the subscribed function will be triggered on all server instances.
Hooks are now split into …
=> Events: Horizontal scaling support in EventStream.subscribe

schemas/migrations/00000001.sql, schemas/migrations/00000002.sql, schemas/migrations/00000003.sql, schemas/migrations/00000004.sql, setup/__main__.py
This pull request includes several important changes to the database migration scripts and setup process. The changes focus on improving the handling of schema modifications, adding warnings for specific operations, and enhancing the logging of migration performance.
- Replaced the `CREATE OR REPLACE FUNCTION` calls with an anonymous `DO` blocks 
- Added `RAISE WARNING` statements to notify about operations being performed
- Optimized functions - removed nested loops, unnecessary calls...
- Restore a VERY old database (Ayon 1.0.0-RC8 or newer). 
- Run the setup
- Everything should work
Or restore an old project dump and run setup....
=> Setup: Optimized migration scripts

api/inbox/inbox.py
This PR enhances the existing `manage_inbox_item` endpoint with `all` argument. Originally, it was necessary to provide a list of ids to manage, now, this list is optional if `all` is set to true - that allows marking the entire inbox as `read` or `inactive` using a single request.
=> Inbox: API enhancements

api/events/enroll.py, api/events/operations.py, api/query/query.py, api/tasks_folders/__init__.py, api/tasks_folders/tasks_folders.py, ayon_server/events/enroll.py, ayon_server/graphql/resolvers/tasks.py, ayon_server/sqlfilter.py
This new endpoint returns a list of folder ids containing tasks matching the given query. This is also a prototype of the proposed query structure that may be adopted for more entity types.
The query supports multiple nested conditions. The `filter` object accepts two parameters:
- **`operator`**: Either `"and"` or `"or"` (defaults to `"and"` if not provided).
- **`conditions`**: A list of conditions, which can either be:
- Another `filter` object (allowing for nested queries).
- A condition object containing `key`, `operator`, and `value`.
Each condition consists of:
- **`key`**: The name of the field (e.g., `status`, `tags`, `assignees`, etc.).
- **`operator`**: A comparison method.
- **`value`**: The value to compare against (if applicable).
| Operator  | Description | …
=> REST: tasksFolders endpoint

ayon_server/graphql/nodes/user.py
Updated the `is_manager` assignment to depend solely on the `isManager` field from the data, rather than also considering the `isAdmin` and `isService` fields.
This makes the result consistent with the REST API
=> GraphQL: return user levels as they are stored in the database

ayon_server/installer/__init__.py
Cosmetic change only.
`enquing` -> `enqueuing`
n/a
Saw this typo in a log.
=> Fix minor typo in logs for installing from market

ayon_server/addons/addon.py, ayon_server/api/dependencies.py, ayon_server/api/server.py
The key changes include adding support for registering routers in the `BaseServerAddon` class and updating the server initialization to include these routers.
* Introduced a new method `add_router` to the `BaseServerAddon` class for adding `APIRouter` 
* Introduced `CurrentAddon` dependency to get the instance of the addon from the endpoint
This adds a way to include multiple addon endpoints in one step and declutter the initialization.
```python
from fastapi import APIRouter
from ayon_server.api.dependencies import CurrentAddon
router = APIRouter()
@router.get("/my-route")
def my_route(addon: CurrentAddon):
return {"message": f"Hello from {addon.name} {addon.version}"}
class MyAddon(BaseServerAddon):
def initialize(self):
self.add_router(router)
```
Route names are created dynamically …
=> API: Routers defined by addons

ayon_server/graphql/nodes/project.py, ayon_server/helpers/tags.py
This pull request introduces a new helper function to the `ayon_server` project, specifically for retrieving project tags from various entities within a project. 
```python
from ayon_server.helpers.tags import get_used_project_tags
all_tags: list[str] = await get_used_project_tags("my-project")
```
=> Helpers: get_used_project_tags helper

api/users/users.py
This pull request includes a crucial change to the `create_user` function in the `api/users/users.py` file. The change adds a validation check to ensure that guest users cannot be service or admin users.
=> Disallow guest users creating guest admins and guest services

api/system/info.py, ayon_server/config/serverconfig.py
Relabel `motd` customization "Message of the Day" to "Login Page Message".
They now live in 2025 instead of the 70s.
The server still lives in the 70s, representing its love for `motd` because the internal key is maintained. 
Upon each login, bold display,
Behold—**Message of the Day!**
From Unix roots, a sysadmin’s lore,
Warnings, jokes, and stats galore.
Before the tweet or status feed,
The `motd` met every need.
But now they brand it, cold and vague,
As "Login Page Message"—what a plague!
A name so lifeless, bland, and grey,
They'll never take **MOTD** away!
=> Relabel `motd` customization "Message of the Day" to "Login Page Message"

api/events/enroll.py, api/services/hosts.py, api/system/info.py, ayon_server/activities/create_activity.py, ayon_server/api/__init__.py, ayon_server/api/authmw.py, ayon_server/api/dependencies.py, ayon_server/api/lifespan.py, ayon_server/api/messaging.py, ayon_server/api/server.py, ayon_server/background/log_collector.py, ayon_server/config/ayonconfig.py, ayon_server/events/eventstream.py, ayon_server/helpers/hierarchy_cache.py, ayon_server/helpers/inherited_attributes.py, ayon_server/logging.py, ayon_server/operations/project_level.py, ayon_server/utils/strings.py
This pull request involves significant changes to the authentication middleware and the initialization of the server, focusing on refactoring and improving the codebase. The most important changes include the removal of deprecated dependencies, the addition of new authentication methods, and the restructuring of the server initialization process.
- Added new authentication middleware to handle user authentication via API keys and access tokens, including methods to extract tokens from requests and validate them.
- Refactored the `dep_current_user` and `dep_current_user_optional` functions to use the new authentication middleware, removing redundant code and improving clarity.
-  Introduced a new lifespan management module to handle server startup and shutdown processes, including loading …
=> API: Unified authentication and logging middleware

api/projects/anatomy.py, api/projects/projects.py, ayon_server/events/patch.py
This pull request introduces a new function to build project change events and integrates it into the existing project update and anatomy setting functionalities. The main goal of these changes is to enhance the event dispatching mechanism when project data is modified.
The following new events are introduced. All of them support audit trail (`oldValue` and `newValue` stored in the event payload)
The original `entity.project.changed` is still being emited to maintain the backwards compatibility (it does not contain the audit trail)
=> Events: emit granular events when project is updated

api/folders/folders.py, api/products/products.py, api/representations/representations.py, api/tasks/tasks.py, api/versions/versions.py, api/workfiles/workfiles.py, ayon_server/operations/common.py, ayon_server/operations/project_level.py, ayon_server/operations/project_level/__init__.py, ayon_server/operations/project_level/entity_create.py, ayon_server/operations/project_level/entity_delete.py, ayon_server/operations/project_level/entity_update.py, ayon_server/operations/project_level/models.py
This pull request refactors the folder, product, representation, and task management operations by replacing direct entity manipulation with the `ProjectLevelOperations` class. This change aims to centralize and simplify the codebase, ensuring consistency and reducing redundancy.
=> REST: Use ProjectLevelOperations in create-update-delete endpoints

api/tasks_folders/tasks_folders.py, ayon_server/graphql/__init__.py, ayon_server/graphql/nodes/folder.py, ayon_server/graphql/nodes/product.py, ayon_server/graphql/nodes/project.py, ayon_server/graphql/nodes/representation.py, ayon_server/graphql/nodes/task.py, ayon_server/graphql/nodes/user.py, ayon_server/graphql/nodes/version.py, ayon_server/graphql/nodes/workfile.py, ayon_server/graphql/resolvers/activities.py, ayon_server/graphql/resolvers/common.py, ayon_server/graphql/resolvers/events.py, ayon_server/graphql/resolvers/folders.py, ayon_server/graphql/resolvers/inbox.py, ayon_server/graphql/resolvers/kanban.py, ayon_server/graphql/resolvers/pagination.py, ayon_server/graphql/resolvers/products.py, ayon_server/graphql/resolvers/projects.py, ayon_server/graphql/resolvers/representations.py, ayon_server/graphql/resolvers/tasks.py, ayon_server/graphql/resolvers/users.py, ayon_server/graphql/resolvers/versions.py, ayon_server/graphql/resolvers/workfiles.py, ayon_server/graphql/utils.py, ayon_server/sqlfilter.py, ayon_server/utils/sqltool.py
This pull request includes several changes to the `graphql` module.
Pagination and sorting was rewritten from scratch and now uses opaque cursors and respect types used for the sorting.
* Added `all_attrib` field to multiple GraphQL node classes (`FolderNode`, `ProductNode`, `ProjectNode`, `RepresentationNode`, `TaskNode`, `UserNode`, `VersionNode`, `WorkfileNode`). This field stores a JSON representation of all attributes user has access to.
* Refactored attribute parsing to use a new `parse_attrib_data` function, which now returns a dictionary instead of an instance of the attribute type. This change affects the `folder_from_record`, `product_from_record`, `project_from_record`, `representation_from_record`, `task_from_record`, `user_from_record`, `version_from_record`, and …
=> GraphQL: New pagination, filtering and sorting by inherited attributes and allAttrib field

api/users/users.py, ayon_server/api/authmw.py, ayon_server/auth/session.py, ayon_server/helpers/rename_user.py
Reason of the "unauthorized" response is logged to the event stream and is returned with 401 responses.
Handling `response.detail` this must now be implemented in the frontend.
=> Provide error messages in 401 responses

ayon_server/graphql/resolvers/users.py, ayon_server/types.py
This pull request introduces new functionality to filter users by email in the GraphQL users resolver. Multiple email addresses can be passed as `emails` argument to the resolver. search is case-insensitive.
=> Filter users by emails in GraphQL

ayon_server/graphql/nodes/activity.py, ayon_server/graphql/resolvers/inbox.py, schemas/schema.public.sql
This PR should reduces the amount of data pulled from the database while resolving user's inbox
- Updated the `get_inbox` resolver to set a context flag indicating that the inbox is being accessed.
- Changed the SQL schema to enforce a 200-character limit on the `body` field in get_user_inbox
=> Inbox: Truncate message body

api/folders/list_folders.py
This pull request introduces significant changes to the `api/folders/list_folders.py` file, focusing on improving the efficiency and structure of folder list retrieval and response building. The most important changes include the introduction of a `FolderListLoader` class, the use of `asyncio` for asynchronous task management, and the replacement of the `StreamingResponse` with a more structured response building method.
* Created the `FolderListLoader` class to manage folder list retrieval with asynchronous task handling and a thread pool executor for improved performance.
* Utilized `asyncio` for managing asynchronous tasks and introduced a lock mechanism to ensure thread-safe operations when fetching folder lists.
* Replaced the `StreamingResponse` with a structured response building …
=> Improved folder list concurency

ayon_server/graphql/nodes/representation.py, ayon_server/graphql/resolvers/representations.py
Adding representation traits to the node in GraphQL.
Traits are JSON serialized data, in GraphQL represented as string to simplify model definitions.
This is done so pipeline code can work with traits retrieved via graphql.
**Related PRs:**
[ayon-core#](https://github.com/ynput/ayon-core/pull/979)
#466
#431
=> Add representation traits to graphql

api/access/access_groups.py, api/folders/list_folders.py, api/tasks_folders/tasks_folders.py, ayon_server/access/access_groups.py, ayon_server/access/utils.py, ayon_server/api/lifespan.py
This pull request includes several significant changes to the access groups and folder access logic in the `api` and `ayon_server` modules. The main improvements involve replacing the `AccessGroups` class with direct database queries, adding event dispatching for access group updates, and refactoring folder access checks to improve performance and clarity.
Access groups changes are now propagated to all running replicas:
=> Support for ACL with horizontal scaling

ayon_server/settings/enum.py
Small enhancements for templates enum for settings.
Removed unnecessary `project_name` argument from enum function `anatomy_template_items_enum`. Whatever would be passed to the function would not be used anyways, so why to bother developer by having argument that does nothing?
Removed outdated information from docstring.
Avoid creation of <dict.Key> -> <list[str]> -> iterable[str] just to extend list.
=> Chore: Templates enum

ayon_server/entities/core/base.py, ayon_server/events/patch.py, ayon_server/operations/project_level/entity_update.py
This pull request includes several changes to the `ayon_server` module, primarily focusing on adding user permission checks and improving event handling for attribute changes. The most important changes are grouped by theme below:
* Added `ForbiddenException` import to `ayon_server/entities/core/base.py` to handle unauthorized attribute modifications.
* Enhanced the `patch` method in `ayon_server/entities/core/base.py` to include user permission checks for attribute modifications, ensuring that unauthorized users cannot modify restricted attributes.
* Improved the `build_pl_entity_change_events` function in `ayon_server/events/patch.py` to better handle old and new attribute values, ensuring accurate event descriptions and payloads for attribute changes.
* Updated the …
=> Use attribute whitelist for entity updates

api/actions/listing.py
This pull request includes a correction to a conditional statement in the `evaluate_simple_action` function within the `api/actions/listing.py` file. This change ensures that the condition properly checks for the `allow_multiselection` attribute of the `action` object.
=> Fixed invalid condition in action multiselection

api/services/hosts.py, api/services/services.py
- Added `NoTraces` as a dependency to the `list_services` endpoint to ensure no traces are logged during service listing.
- Updated the `PatchServiceRequestModel` class to include a `hostname` field and marked the `config` field as deprecated for backwards compatibility.
- Refactored the `patch_service` function to handle service data updates more efficiently, including updating fields such as `should_run`, `hostname`, and nested `config` fields.
This is a backend counterpart to https://github.com/ynput/ayon-frontend/pull/1094
=> Polished service configuration updates

api/addons/common.py, api/addons/project_settings.py, api/addons/studio_settings.py, api/settings/settings.py
This pull request introduces a new `user_name` parameter to several functions across multiple files to enhance user-specific tracking and logging. Additionally, it improves error logging for missing addons by including more descriptive bundle titles.
=> Propagate user to settings.changed events

ayon_server/graphql/resolvers/activities.py, ayon_server/graphql/resolvers/pagination.py
This pull request introduces minor logging enhancements and a new feature to handle ISO timestamp values in cursor decoding for GraphQL resolvers. 
Added a regular expression check to identify ISO timestamp values in the `decode_cursor` function. If a match is found, the value is converted to a PostgreSQL `timestamptz` format for proper handling.
=> Use timestamptz casting when sorting timestamps

api/projects/__init__.py, api/projects/tags.py
This pull request introduces a new feature to support retrieving tags associated with various project entities. The changes include adding a new API endpoint and updating the project module imports to include the new functionality.
* **Added a new API endpoint to list tags for a project**: Introduced the `get_project_tags` function in `api/projects/tags.py`, which queries the database to retrieve distinct tags for various project entities (folders, tasks, products, versions, representations, and workfiles). The endpoint returns the tags in a structured format defined by the new `ProjectTagsModel` class.
=> Get project tags endpoint

api/bundles/migration.py, ayon_server/addons/addon.py
Added validation to ensure `source_variant` and `target_variant` are either "production" or "staging," or match their respective bundles when not. If these conditions are not met, a `BadRequestException` is raised.
=> Sanity check for dev bundle settings migration

api/anatomy/__init__.py
This pull request introduces several updates to the `api/anatomy/__init__.py` file, primarily focusing on simplifying database transaction handling and adding a new feature for renaming anatomy presets. The most significant changes include replacing nested transaction handling with a streamlined approach, introducing a new endpoint for renaming presets, and ensuring consistency in permission checks.
This requires a frontend counterpart.
=> Renaming anatomy presets

ayon_server/forms/simple_form.py
This pull request refactors the `SimpleFormField` class in `ayon_server/forms/simple_form.py` to improve type safety and maintainability by introducing stricter type definitions using Pydantic's `Strict*` types. The most important changes include the addition of a new `ValueType` union and the replacement of the `value` field's type with this new definition.
=> Use pydantic strict types for simple form values

ayon_server/api/logging.py, ayon_server/graphql/__init__.py, ayon_server/graphql/nodes/entity_list.py, ayon_server/graphql/resolvers/entity_list_items.py, ayon_server/graphql/resolvers/entity_lists.py, ayon_server/sqlfilter.py
This pull request introduces significant enhancements to the filtering and sorting capabilities of the `entity_list_items` query in the GraphQL API, along with related changes to improve maintainability and functionality. The most important updates include adding a new `filter` parameter to support advanced filtering, refactoring column naming conventions for consistency, and implementing unified attributes for sorting and filtering. 
For filtering and sorting `attrib` field unifies entity attributes with list items attributes:
Assuming we're loading a list of tasks:
```graphql
items(sortBy: "attrib.priority"){
...
}
```
Sorting will use the following fields to determine the actual value to sort by in this order:
- list item attribute (if the priority is set on the item level)
- task …
=> Entity list items filtering

api/actions/listing.py, ayon_server/actions/context.py, ayon_server/entity_lists/entity_list.py
This pull request updates the `ActionContext` class in `ayon_server/actions/context.py` to include support for a new entity type, `"list"`. It also adjusts the logic in the `get_entities` method to account for this addition.
- always includes the contained entity type (version, folder, etc.)
- optionally includes the list type: "version:review-session"
always includes both parts: "version:review-session"
An action_subtype matches a context_subtype if:
- The contained type matches (version == version)
- If action_subtype includes a list type, it must also match (review-session)
- If action_subtype doesn't include a list type,  it's considered a wildcard (matches all list types  of that entity type)
manifest subtype | context subtype | Match?
-- | -- | --
`version` | …
=> List actions

api/addons/list_addons.py, api/system/frontend_modules.py, ayon_server/addons/addon.py, ayon_server/addons/models.py
This pull request introduces new type definitions for `FrontendScopes` and `FrontendModules` in the `ayon_server.addons.models` module and updates their usage across several files to improve type safety and consistency. The changes primarily focus on replacing generic dictionary types with these new type definitions.
=> Typing: FrontendScopes and FrontendModules models

ayon_server/settings/anatomy/templates.py
-   [ ] Referenced issue is linked
Update default hero template to contain match default publish template but with version swapped to `hero`
It's good to be aware that this may introduce more complexities because with hero version publishes it may be the case that previous hero versions had different frames and as such, it may occur that 'frames' that _should not_ be there anymore do not actually belong to the new version - same goes for UDIMs.
What becomes worse then is if e.g. a path set inside a DCC just happens to be referring to e.g. a start frame of the hero that's not supposed to be there in the new version. Which means you're basically potentially losing the 'static' nature of what a hero version tries to be? **This is why I'm …
=> Settings: Update default hero publish template to include frame and udim

ayon_server/graphql/resolvers/common.py, ayon_server/graphql/resolvers/entity_list_items.py
hasReviewables flag on fragments was not populated in version entity list. this is now fixed, so it is possible to get this information per entity list item.
=> hasReviewables node on version entity list items

ayon_server/attributes/models.py
This pull request introduces a validation method for the `enum` field in the `AttributeData` model to ensure proper handling of its values: Added the `validate_enum` method to validate the `enum` field, ensuring it returns `None` if the value is empty or not a list.
=> Fixed attribute emtpy enums handling

ayon_server/activities/create_activity.py, ayon_server/activities/delete_activity.py, ayon_server/activities/models.py, ayon_server/activities/update_activity.py
This pull request introduces a mechanism to distinguish between activities that should or should not be stored in the database, along with updates to event dispatch logic in several activity-related functions. The key changes include adding a `DO_NOT_TRACK_ACTIVITIES` set to specify activities excluded from database storage, modifying event payloads, and updating descriptions for dispatched events.
This PR allows comments to be handled by services
=> Log activities in the event stream

api/thumbnails/thumbnails.py
This pull request refactors thumbnail retrieval logic in the `api/thumbnails/thumbnails.py` file to improve efficiency and functionality. Key changes include replacing redundant methods with optimized SQL queries, enhancing thumbnail fallback mechanisms, and removing unused imports and caching decorators.
* Refactored `async def get_folder_thumbnail` to use a new SQL query that retrieves folder thumbnails, version thumbnails, and reviewable thumbnails in one operation, improving efficiency and adding fallback mechanisms for missing thumbnails.
* Refactored `async def get_task_thumbnail` with a similar optimized SQL query to retrieve task thumbnails, version thumbnails, and reviewable thumbnails, while enhancing fallback logic for missing thumbnails.
* Removed the …
=> Fallback to reviewable preview when thumbnail is not set for folder/task

api/users/users.py, ayon_server/auth/password.py, ayon_server/graphql/nodes/user.py
This pull request introduces a new feature to support disabling password login for users, along with updates to ensure proper handling of this functionality across the codebase. The key changes include adding a `disable_password_login` attribute to the `UserNode` class, updating logic in user authentication and mutation methods, and ensuring the attribute is correctly populated from user records.
Disabling password login is useful when a more secure SSO is required for user authentication
=> Option to disable password login

ayon_server/graphql/resolvers/entity_list_items.py
This pull request updates the SQL query logic in the `get_entity_list_items` function to improve robustness and handle potential null values more effectively. Key changes include switching join types and using `COALESCE` to provide default values for JSONB columns.
* Changed `INNER JOIN` to `LEFT JOIN` for `project_{project_name}.exported_attributes` and `project_{project_name}.folders` to ensure that rows are included even if there are no matching entries in the joined tables.
* Added `COALESCE` to handle potential null values in `px.attrib` for both "folder" and "task" entity types, ensuring that empty JSONB objects (`'{}'::JSONB`) are used as defaults.
These changes enhance the query's resilience and ensure data consistency when dealing with optional attributes.
=> Fixed root folders propagation to entity lists

ayon_server/graphql/resolvers/folders.py, ayon_server/graphql/resolvers/products.py, ayon_server/graphql/resolvers/representations.py, ayon_server/graphql/resolvers/versions.py, ayon_server/sqlfilter.py
This pull request introduces a filtering mechanism across multiple GraphQL resolvers (`folders.py`, `products.py`, `representations.py`, and `versions.py`) to enable advanced querying capabilities using `QueryFilter`. 
It enables filtering by attribute using various fields, operators and nested conditions:
SQLFilter syntax is described here 
- https://github.com/ynput/ayon-backend/pull/507
- https://github.com/ynput/ayon-backend/pull/568
Filter representations by a partial path
```graphql
query q {
project(name:"AY_CG_demo"){
representations(filter:"{\"conditions\":[{\"key\": \"attrib.path\", \"operator\":\"like\", \"value\":\"%cg_pigeon_model%\"}]}"){
edges{
node{
name
attrib {
path
}
}
}
}
}
}
```
Get versions with version number higher than 2
```graphql
query q { …
```
=> GraphQL: Advanced filtering in entity resolvers

api/folders/list_folders.py, ayon_server/activities/create_activity.py, ayon_server/entities/folder.py, ayon_server/entities/task.py, ayon_server/helpers/hierarchy_cache.py
This pull request introduces changes to support the concept of "reviewables" in the hierarchy cache and related functionality. Key updates include adding the `has_reviewables` attribute to folder entities, modifying the hierarchy cache logic to account for reviewables, and simplifying the `rebuild_hierarchy_cache` function by removing the `transaction` parameter. Below is a breakdown of the most important changes.
It may be necessary to do at least some write operation in the project to invalidate the current hierarchy cache
=> REST:  hasReviewables flag in list_folders endpoint

ayon_server/graphql/nodes/project.py
This pull request introduces several enhancements to the `ayon_server/graphql/nodes/project.py` file to improve the GraphQL schema and query logic. The changes include adding new fields to existing types, creating a new type (`LinkType`), and updating query methods to handle additional data attributes. These updates enhance the flexibility and functionality of the project schema.
* Added optional fields `icon`, `short_name`, and `color` to `TaskType` and `FolderType`, allowing for richer metadata representation.
* Introduced a new `LinkType` with fields such as `name`, `link_type`, `input_type`, `output_type`, `color`, and `style`, expanding the schema to support link-related data.
* Updated the `task_types` and `folder_types` methods to include additional attributes (`short_name`, …
=> GraphQL: Additional anatomy-related fields for project node

ayon_server/api/server.py
Added two new endpoints (`/openapi.json` and `/docs`) to serve OpenAPI schema and documentation. Access to these endpoints is restricted to manager-level users and disabled when REST documentation is turned off.
=> Require authentication for openapi docs by default

api/actions/actions.py, api/actions/listing.py
-   [ ] `/api/actions/list` endpoint allows to explicitly define settings variant.
It was not possible to receive actions for explicitly defined settings variant which is a big issue for pipeline purposes. There was no way how to get `staging` actions, or actions for specific dev bundle.
The endpoint is backwards compatible and still works as before until the `variant` query is passed to the endpoint.
Resolves https://github.com/ynput/ayon-backend/issues/651
=> Actions: List actions endpoint allows to specify settings variant

ayon_server/graphql/__init__.py, ayon_server/graphql/dataloaders/__init__.py, ayon_server/graphql/nodes/common.py, ayon_server/graphql/nodes/folder.py, ayon_server/graphql/nodes/product.py, ayon_server/graphql/nodes/representation.py, ayon_server/graphql/nodes/task.py, ayon_server/graphql/nodes/version.py, ayon_server/graphql/nodes/workfile.py, ayon_server/graphql/resolvers/products.py, ayon_server/graphql/resolvers/representations.py, ayon_server/graphql/resolvers/tasks.py, ayon_server/graphql/resolvers/versions.py, ayon_server/graphql/resolvers/workfiles.py
Added a `path` field to `ProductNode`, `RepresentationNode`, `TaskNode`, `VersionNode`, and `WorkfileNode` to store hierarchical path information. Introduced a `parents` field to compute parent elements based on the path.
This pull request enhances the GraphQL data loading and node structure in the `ayon_server` project by adding support for hierarchical paths and parent relationships. These changes improve data querying capabilities and enable more detailed representations of entities like products, tasks, versions, and workfiles. Key updates include modifications to data loaders, node definitions, and resolvers.
=> GraphQL: expose parents (and path) fields on all project level entity nodes

ayon_server/operations/project_level/entity_update.py
Use `force` flag to allow changing folder name and parent even when it has published versions.
* Added a new helper function `sanitize_folder_update` to encapsulate the logic for sanitizing folder update operations. This function ensures that only allowed fields are updated and raises a `ForbiddenException` if changes are attempted on restricted fields for folders with published versions.
* Replaced the inline folder sanitization logic in the `update_project_level_entity` function with a call to the newly introduced `sanitize_folder_update` function, streamlining the code and reducing duplication.
=> Force update improvements in entity operations

ayon_server/entities/folder.py, ayon_server/graphql/resolvers/folders.py, ayon_server/helpers/hierarchy_cache.py
This pull request refactors how the `has_versions` and `has_reviewables` flags are determined for folders throughout the backend, making the logic more efficient and consistent by leveraging recursive SQL queries. The main improvement is that instead of checking only the direct folder, hasVersion flag now account for all descendant folders using recursive common table expressions (CTEs). Additionally, the SQL queries are optimized and unified across different modules.
hasVersion flag is used to determine whether a folder can be renamed, moved or deleted, so it makes sense to check the descendatnts as well.
=> Recursive version check for folders

ayon_server/graphql/resolvers/tasks.py
This pull request refactors and optimizes the SQL query logic in the `get_tasks` GraphQL resolver. The main improvements include more efficient SQL joins, enhanced sorting capabilities (notably by custom task type order), and improved handling of sorting stability. These changes make the resolver more performant and flexible, especially when handling large task datasets or complex queries.
* Added a new function `get_task_types_sort_case` to enable sorting tasks by their type in the order defined in the project's anatomy, supporting more user-friendly and project-specific task listings.
* Improved the logic for setting the `order_by` clause: now uses `tasks.creation_order` for stable default sorting, and adds a secondary sort by path/name when a single sort criterion is specified, …
=> GraphQL: Improved task sorting

api/access/utils.py, ayon_server/helpers/project_list.py
* Added a new async function `normalize_project_name` in `ayon_server/helpers/project_list.py` to standardize project names by matching case-insensitively and returning the canonical case-sensitive name.
* Updated the `get_share_options` function in `api/access/utils.py` to use `normalize_project_name` before fetching share options, ensuring consistent project name handling.
=> Normalize project name helper
